export const memolibTermsOfUse = `
<h1 class="privacy-title">Terms of Use for MemoLib</h1>
<p class="last-updated">Last updated: January 13, 2026</p>

<h2>1. Acceptance of Terms</h2>
<p>
    By accessing or using <strong>MemoLib</strong> ("the App", "the Service"), you agree to be bound by these 
    <strong>Terms of Use</strong>.
</p>
<p>
    If you do not agree to these terms, you may not use the Service.
</p>

<h2>2. Description of the Service</h2>
<p>
    MemoLib is an application that transforms various content sources into audio playlists for learning by listening.
</p>
<p>
    Users can:
</p>
<ul>
    <li>Upload PDF documents, photos, and audio files</li>
    <li>Link YouTube videos</li>
    <li>Generate high-quality audio playlists from uploaded content</li>
    <li>Listen to content anytime, anywhere</li>
</ul>
<p>
    MemoLib is designed for auditory learners who want to consume educational content efficiently.
</p>

<h2>3. Eligibility</h2>
<p>
    You must be at least <strong>16 years old</strong> (or the minimum age required by law in your jurisdiction) to use MemoLib.
</p>
<p>
    By using the Service, you represent that you meet this requirement.
</p>

<h2>4. User Accounts</h2>
<p>
    To access MemoLib, you must create an account using one of the supported authentication methods.
</p>
<p>
    You are responsible for:
</p>
<ul>
    <li>Maintaining the confidentiality of your account credentials</li>
    <li>All activities that occur under your account</li>
    <li>Ensuring your account information is accurate and up-to-date</li>
</ul>
<p>
    MemoLib is not responsible for unauthorized access caused by your failure to secure your account.
</p>

<h2>5. User Content</h2>

<h3>5.1 Content You Upload</h3>
<p>
    By uploading files or linking content to MemoLib, you confirm that:
</p>
<ul>
    <li>You own the content or have the right to use it</li>
    <li>Your use does not violate any applicable laws or third-party rights</li>
    <li>The content does not contain illegal, harmful, or offensive material</li>
</ul>
<p>
    You retain ownership of any content you upload.
    However, you grant MemoLib a <strong>limited, non-exclusive license</strong> to process, store, and convert 
    the content solely for the purpose of providing the Service.
</p>

<h3>5.2 Prohibited Use</h3>
<p>
    You agree not to:
</p>
<ul>
    <li>Upload content that infringes copyrights or other intellectual property rights</li>
    <li>Use the Service for unlawful purposes</li>
    <li>Upload malicious files (viruses, malware, etc.)</li>
    <li>Attempt to reverse engineer, abuse, or overload the Service</li>
    <li>Share or distribute copyrighted content unlawfully</li>
</ul>

<h2>6. Storage and File Limits</h2>
<p>
    MemoLib may impose limits on:
</p>
<ul>
    <li>File upload sizes</li>
    <li>Total storage capacity per user</li>
    <li>Number of playlists or audio files</li>
</ul>
<p>
    These limits may vary depending on your subscription plan (if applicable).
</p>

<h2>7. AI-Generated Content Disclaimer</h2>
<p>
    Audio playlists and transcriptions generated by MemoLib are produced using artificial intelligence and text-to-speech technology.
</p>
<ul>
    <li>AI-generated content may contain errors or inaccuracies</li>
    <li>MemoLib does <strong>not guarantee perfect accuracy</strong> of transcriptions or audio quality</li>
    <li>The content is provided <strong>for informational and educational purposes only</strong></li>
</ul>
<p>
    You are responsible for how you use the generated content.
</p>

<h2>8. Intellectual Property</h2>
<p>
    All rights, title, and interest in the MemoLib application, including software, design, branding, and underlying 
    technology, remain the exclusive property of <strong>MemoLib / Leonardo Granetto</strong>.
</p>
<p>
    You may not copy, modify, distribute, or exploit any part of the Service without prior written permission.
</p>

<h2>9. Availability and Changes</h2>
<p>
    MemoLib is provided on an <strong>"as is"</strong> and <strong>"as available"</strong> basis.
</p>
<p>
    We reserve the right to:
</p>
<ul>
    <li>Modify or discontinue parts of the Service</li>
    <li>Introduce storage limits or usage restrictions</li>
    <li>Update or change features at any time</li>
    <li>Perform maintenance that may temporarily interrupt service</li>
</ul>
<p>
    We do not guarantee uninterrupted or error-free operation.
</p>

<h2>10. Termination</h2>
<p>
    We may suspend or terminate your access to MemoLib at any time if:
</p>
<ul>
    <li>You violate these Terms</li>
    <li>Your use poses a risk to the Service or other users</li>
    <li>We are legally required to do so</li>
    <li>Your account remains inactive for an extended period</li>
</ul>
<p>
    You may stop using the Service and delete your account at any time.
    Upon deletion, your uploaded files and playlists will be permanently removed.
</p>

<h2>11. Limitation of Liability</h2>
<p>
    To the maximum extent permitted by law:
</p>
<ul>
    <li>MemoLib shall not be liable for indirect, incidental, or consequential damages</li>
    <li>MemoLib is not responsible for loss of data, loss of files, or reliance on AI-generated content</li>
    <li>MemoLib is not liable for copyright infringement by users who upload infringing content</li>
</ul>
<p>
    Your use of the Service is at your own risk.
</p>

<h2>12. Indemnification</h2>
<p>
    You agree to indemnify and hold harmless MemoLib from any claims, damages, or expenses arising from:
</p>
<ul>
    <li>Your misuse of the Service</li>
    <li>Your violation of these Terms</li>
    <li>Your violation of any third-party rights (including copyright infringement)</li>
    <li>Content you upload or share through the Service</li>
</ul>

<h2>13. Governing Law</h2>
<p>
    These Terms are governed by the laws of the <strong>Federal Republic of Germany</strong>, excluding its conflict-of-law provisions.
</p>

<h2>14. Changes to These Terms</h2>
<p>
    We may update these Terms of Use from time to time.
    Continued use of MemoLib after changes become effective constitutes acceptance of the updated Terms.
</p>

<h2>15. Contact</h2>
<p>
    If you have any questions regarding these Terms, please contact:
</p>
<div class="contact-info">
    <p>
        <strong>Leonardo Granetto</strong><br>
        📧 <strong>Email:</strong> <a href="mailto:LeonardoGranetto@gmail.com">LeonardoGranetto@gmail.com</a><br>
        Biebricher Straße 7f<br>
        55252 Mainz-Kastel<br>
        Germany
    </p>
</div>
`;
